### ISSUE TITLE
Add multi-language support

### ISSUE THREAD

**Issue by justcool393** [justcool393/TotesMessenger#12]
Some subreddits are mostly spoken in a different language, and this feature would be a good one to have. It's currently being tested in the private /r/TMTest subreddit as of now.

**Comment by hidde-jan** [comment]
Could you open a pull request for this feature? Just create a new branch, push the commits you've done to it and create a PR.

**Comment by justcool393** [comment]
It's on the feature-translations branch. I've done some testing on the TotesTest account, and it seems to work okay.
