### ISSUE TITLE
Remove No Participation links from TotesMessenger

### ISSUE THREAD

**Issue by justcool393** [justcool393/TotesMessenger#18]
No participation or "NP" links often give the false impression that voting or commenting is disabled, is required by reddit, and/or is useful to a majority of users. These links do not work on mobile apps or the mobile web, and as such, can be misleading to other users.

**Comment by jmontreal** [comment]
So, why remove them?, and remove them how?, do you mean, "not list them in a TotesMessenger comment"?

I'm trying to understand why you wouldn't want to offer them? 

Perhaps it'd be effective, and serve your goal, to signal them as NP and stress that they've requested non-participation instead?

**Comment by hidde-jan** [comment]
We will just use www.reddit.com instead of np.reddit.com as the hostsname. 

NP links have been proven to be ineffective in any way and have been abandoned as a means by almost all meta subreddits. 

We ask people not to vote in linked threads in every comment by the bot. That should be enough.

**Comment by jmontreal** [comment]
That makes sense!
I'm glad you're not ignoring those.

Good work, by the way, I'm impressed with the project. The updating of the bot's comments to collect all x-posts into one comment, *and* alphabetize them are really refined behaviors.

Keep up the good work!

**Comment by justcool393** [comment]
This has been done.
