### ISSUE TITLE
Use non-participation links

### ISSUE THREAD

**Issue by russjr08** [justcool393/TotesMessenger#4]
As the bot comments, users shouldn't vote on submissions that are linked.

To further help this, maybe the non-participation link should be used? (np.reddit.com/r/sub/etc) That way, users who use RES will be warned about voting.

**Comment by justcool393** [comment]
No Participation links should already be used when comments are made by the bot.

**Comment by russjr08** [comment]
http://www.reddit.com/user/TotesMessenger

If you check the links that the bot posts, it doesn't.

I also checked the source and don't think I saw any mention of it, I'm not that great at python however though, so take that with a grain of salt lol

**Comment by justcool393** [comment]
Oh, I see. It was posting with NP links a little bit ago, but I must have done something to undo that. It'll be fixed when I move over the code used in production to the new codebase.

**Comment by justcool393** [comment]
Fixed in 50ccd0104e07ffbe354357859994ba6732478f7d
