### ISSUE TITLE
Links mess up when there are multiple brackets

### ISSUE THREAD

**Issue by justcool393** [justcool393/TotesMessenger#7]
From reddit: http://www.reddit.com/r/TotesMessenger/comments/31h75g/links_mess_up_when_there_are_multiple_brackets/

![Image showing bugged TotesMessenger post](http://i.imgur.com/QCzluDG.jpg)

Quote:

> I encountered this post imgur
> 
> just now and it has some minor formatting problems.
> 
> Here's the markdown of the post (I think; I got it form the API but might not have unescaped it right)
> 
> This thread has been linked to from another place on reddit.
> - [/r/HailCorporate] [TIL this luxury brand that makes watches donates to charities. Nevermind the top comment](http://www.reddit.com/r/HailCorporate/comments/31ephq/til_this_luxury_brand_that_makes_watches_donates/)
> - [/r/Watches] [[Rolex] [x-post fro TIL] Rolex is run by a non-profit.](http://www.reddit.com/r/Watches/comments/31f3gk/rolex_xpost_fro_til_rolex_is_run_by_a_nonprofit/)
> - [/r/Shitstatistssay] [This whole thread. Unbelievable. Donating is apparently less laudable than paying taxes.](http://www.reddit.com/r/Shitstatistssay/comments/31f5ui/this_whole_thread_unbelievable_donating_is/)
> 
> [](#footer)_^If ^you ^follow ^any ^of ^the ^above ^links, ^respect ^the ^rules ^of ^reddit ^and ^don't ^vote. ^([Info](/r/TotesMessenger/wiki/) ^/ ^[Contact](/message/compose/?to=/r/TotesMessenger))_ [](#bot)
> 
> And here's the post itself:
> 
> ```
> This thread has been linked to from another place on reddit.
> 
> 
> 
>     [/r/HailCorporate] TIL this luxury brand that makes watches donates to charities. Nevermind the top comment
> 
> 
> 
>     [/r/Watches] [[Rolex] x-post fro TIL] Rolex is run by a non-profit.
> 
> 
> 
>     [/r/Shitstatistssay] This whole thread. Unbelievable. Donating is apparently less laudable than paying taxes.
> 
> 
> 
> If you follow any of the above links, respect the rules of reddit and don't vote. (Info / Contact)
> ```
> 
> The problematic line is this:
> - [/r/Watches] [[Rolex] [x-post fro TIL] Rolex is run by a non-profit.](http://www.reddit.com/r/Watches/comments/31f3gk/rolex_xpost_fro_til_rolex_is_run_by_a_nonprofit/)
>   
>   ```
>   [/r/Watches] [[Rolex] x-post fro TIL] Rolex is run by a non-profit.
>   ```
> 
> It needs to have the opening braces escaped too, as otherwise the second one is treated as the start.
> - [/r/Watches] [[Rolex] [x-post fro TIL] Rolex is run by a non-profit.](http://www.reddit.com/r/Watches/comments/31f3gk/rolex_xpost_fro_til_rolex_is_run_by_a_nonprofit/)
>   
>   ```
>   [/r/Watches] [Rolex] [x-post fro TIL] Rolex is run by a non-profit.
>   ```
> 
> This is minor, but it seems like something worth mentioning. Thanks!

**Comment by hidde-jan** [comment]
This is not fixed in the rewrite, it just renders the title between the brackets. You can fix this by writing a small helper function like `np` that uses str.replace to change every [ to \[ and ] to \]. Then wrap the title at [0] in that function, similar to permalink. 

[0] https://github.com/justcool393/TotesMessenger/blob/master/totes.py#L355

**Comment by justcool393** [comment]
Wrong issue mentioned in messages. Fixed in 2b13c8ce5ace971931d0d7271681f1581f748afb
