### ISSUE TITLE
Source subreddits aren't ignored.

### ISSUE THREAD

**Issue by justcool393** [justcool393/TotesMessenger#8]
Subreddits that are on the source ignore list don't get ignored when posting.

Examples:
http://www.reddit.com/r/todayilearned/comments/31h9n9/./cq1pzmg
http://www.reddit.com/r/mylittlepony/comments/31hwjd/./cq1pse0

![](http://i.imgur.com/ro4YebU.png)

**Comment by hidde-jan** [comment]
I couldn't figure out the src vs non src names. Source is the thing getting linked, link is the linking post. Let me check what happened here.

**Comment by justcool393** [comment]
@hidde-jan From what I see, it seems that the `SKIP_LINK` and `SKIP_SOURCE` blacklists got swapped.

**Comment by hidde-jan** [comment]
Ok, please feel free to swap them back :p

**Comment by hidde-jan** [comment]
Btw you can create the db and fill it on heroku by provisioning a free postgres db, then running

```
heroku run python db.py create populate
```

Cheers

**Comment by hidde-jan** [comment]
My thought was
- if the bot is banned, or the sub is in skip_source, don't post a notification to the post / comment
- if the sub of the submission that links to a post / comment is in skip_link list, don't list it in the notification. 

I think my lists also miss some of the subs you added after I started coding.

**Comment by hidde-jan** [comment]
Checked your code again. My link object is your source. Sorry for confusing stuff. Just swapping the lists and recreating the db should fix it.

**Comment by justcool393** [comment]
Yup, it seems that way. :+1:
Seems to be fixed and I think the database is fixed as well. (2b13c8ce5ace971931d0d7271681f1581f748afb)
